#!/usr/bin/env bash
set -euo pipefail

# prompt for sudo credentials upfront
sudo -v

echo "Installing latest Brave Origin Nightly..."
sudo curl -fsSLo /usr/share/keyrings/brave-browser-nightly-archive-keyring.gpg https://brave-browser-apt-nightly.s3.brave.com/brave-browser-nightly-archive-keyring.gpg
sudo curl -fsSLo /etc/apt/sources.list.d/brave-browser-nightly.sources https://brave-browser-apt-nightly.s3.brave.com/brave-browser.sources
sudo apt update
sudo apt install -y brave-origin-nightly

echo "Brave Origin Nightly $(brave-origin-nightly --version) installed"
