#!/usr/bin/env bash
set -euo pipefail

echo "Installing latest rust toolchain..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path

echo "rustc $(~/.cargo/bin/rustc --version) installed"
