require("nvim-treesitter.config").setup({
  ensure_installed = {
    "bash",
    "javascript",
    "typescript",
    "tsx",
    "python",
    "lua",
    "json",
    "yaml",
    "toml",
    "markdown",
    "markdown_inline",
    "html",
    "css",
    "php",
    "gitcommit",
    "gitignore",
  },
  auto_install = true,
  highlight = { enable = true },
  indent = { enable = true },
})
